onlyBuiltDependencies:
  - '@playwright/browser-chromium'
  - esbuild
  - sharp
  - workerd

minimumReleaseAge: 10080 # 7 days

allowBuilds:
  '@playwright/browser-chromium': true
  esbuild: true
  sharp: true
  workerd: true
