name: pull-request
on: pull_request

jobs:
  preview-pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: setup pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      - name: pnpm install
        run: pnpm install
      - name: build pdf
        run: pnpm run export:pdf
      - name: upload pdf to artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: 'resume.pdf'
          path: 'resume.pdf'
