name: pull-request
on: pull_request

jobs:
  preview-pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - name: pnpm install
        run: pnpm install
      - name: build pdf
        run: pnpm run export:pdf
      - name: upload pdf to artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: 'resume.pdf'
          path: 'resume.pdf'
